//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Locations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comp_Locations()
        {
            this.Inv_SaleCreditReceive = new HashSet<Inv_SaleCreditReceive>();
            this.Inv_Store = new HashSet<Inv_Store>();
            this.Inv_POMapping = new HashSet<Inv_POMapping>();
            this.Lse_CashCollection = new HashSet<Lse_CashCollection>();
            this.Lse_ExpenseTransaction = new HashSet<Lse_ExpenseTransaction>();
            this.Lse_SaleTarget = new HashSet<Lse_SaleTarget>();
            this.Pay_EmpLocationMapping = new HashSet<Pay_EmpLocationMapping>();
            this.Lse_Master = new HashSet<Lse_Master>();
        }
    
        public int LocId { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string Address { get; set; }
        public int CityId { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public int LocTypeId { get; set; }
        public string Department { get; set; }
        public bool Status { get; set; }
        public Nullable<int> OldLocId { get; set; }
        public Nullable<int> OldCashLocId { get; set; }
        public string OldLocCode { get; set; }
        public string OldLocName { get; set; }
        public Nullable<int> PurchaseCenter { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public string OldDBName { get; set; }
        public Nullable<int> CashCenter { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<int> Ext { get; set; }
        public Nullable<int> FBRPOSID { get; set; }
        public Nullable<int> FreshMonth { get; set; }
        public Nullable<System.DateTime> PhaseOutDate { get; set; }
        public decimal Opening { get; set; }
        public Nullable<decimal> Insurance { get; set; }
    
        public virtual Comp_City Comp_City { get; set; }
        public virtual Comp_LocationType Comp_LocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SaleCreditReceive> Inv_SaleCreditReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Store> Inv_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POMapping> Inv_POMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_CashCollection> Lse_CashCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_ExpenseTransaction> Lse_ExpenseTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_SaleTarget> Lse_SaleTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpLocationMapping> Pay_EmpLocationMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Master> Lse_Master { get; set; }
    }
}
