//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_LocationIP
    {
        public int RowId { get; set; }
        public int LocId { get; set; }
        public string IP { get; set; }
        public bool Status { get; set; }
        public string ToIP { get; set; }
        public string Type { get; set; }
    }
}
