//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_GeoLocation
    {
        public int GeoId { get; set; }
        public string GTitle { get; set; }
        public int ParentId { get; set; }
        public string GLevel { get; set; }
        public int Status { get; set; }
    }
}
