//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comp_City()
        {
            this.Inv_SuppliersCity = new HashSet<Inv_SuppliersCity>();
            this.Comp_Locations = new HashSet<Comp_Locations>();
        }
    
        public int CityId { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SuppliersCity> Inv_SuppliersCity { get; set; }
        public virtual Comp_Region Comp_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comp_Locations> Comp_Locations { get; set; }
    }
}
