//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_DocTransfer
    {
        public int TransId { get; set; }
        public int FromLocId { get; set; }
        public int ToLocId { get; set; }
        public string Title { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<System.DateTime> RecvDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> RecvBy { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
