//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Documents
    {
        public long DocId { get; set; }
        public int DocTypeId { get; set; }
        public long RefObjId { get; set; }
        public string DocName { get; set; }
        public string Extension { get; set; }
        public string DocPath { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public long Size { get; set; }
    }
}
