//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_DocShare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comp_DocShare()
        {
            this.Comp_DocShareDetail = new HashSet<Comp_DocShareDetail>();
        }
    
        public long TransId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comp_DocShareDetail> Comp_DocShareDetail { get; set; }
    }
}
