//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_LocationsMapping
    {
        public int GeoId { get; set; }
        public int EmpId { get; set; }
        public bool MappingStatus { get; set; }
        public int MappedBy { get; set; }
        public System.DateTime MappedDate { get; set; }
    }
}
