//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Profile
    {
        public int CompId { get; set; }
        public string CompName { get; set; }
        public string CompDescription { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string GSTNumber { get; set; }
        public string GSTLineText { get; set; }
        public string CustomerUndertaking { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<int> MobileAppVersion { get; set; }
        public Nullable<int> UtilityVersion { get; set; }
        public Nullable<long> BankSlipCounter { get; set; }
    }
}
