//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_DocShareDetail
    {
        public long TransDtlId { get; set; }
        public long TransId { get; set; }
        public int LocId { get; set; }
        public string ReceivedBy1 { get; set; }
        public string ReceivedBy2 { get; set; }
        public string ReceivedBy3 { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Comp_DocShare Comp_DocShare { get; set; }
    }
}
