//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Response
    {
        public long RowId { get; set; }
        public long TicketId { get; set; }
        public string Response { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Crm_Ticket Crm_Ticket { get; set; }
        public virtual Users_Login Users_Login { get; set; }
    }
}
