//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crm_Ticket()
        {
            this.Crm_Respondent = new HashSet<Crm_Respondent>();
            this.Crm_Response = new HashSet<Crm_Response>();
        }
    
        public long TicketId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public int CategoryId { get; set; }
        public string Complain { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
        public int LocId { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> CloseBy { get; set; }
        public string Priority { get; set; }
    
        public virtual Crm_Category Crm_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crm_Respondent> Crm_Respondent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crm_Response> Crm_Response { get; set; }
    }
}
