//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Far_Allocation
    {
        public long TransId { get; set; }
        public long StoreId { get; set; }
        public int FromCCCode { get; set; }
        public int ToCCCode { get; set; }
        public int FromEmpId { get; set; }
        public int ToEmpId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
    }
}
