//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Far_Depreciation
    {
        public long RowId { get; set; }
        public long StoreId { get; set; }
        public System.DateTime Month { get; set; }
        public int CCCode { get; set; }
        public decimal DeprAmt { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    }
}
