//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Far_Store
    {
        public long StoreId { get; set; }
        public int ItemId { get; set; }
        public string SerialNo { get; set; }
        public System.DateTime TransDate { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
        public int LocId { get; set; }
        public int EmpId { get; set; }
        public string Condition { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public decimal PPrice { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal CurrentValue { get; set; }
        public int DepreciationMethod { get; set; }
        public decimal DepreciationPercent { get; set; }
        public int CCCode { get; set; }
        public int SuppId { get; set; }
        public string ItemType { get; set; }
        public int CostTypeId { get; set; }
        public Nullable<long> InvId { get; set; }
        public string CSerialNo { get; set; }
    }
}
