//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_PaymentAdvice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_PaymentAdvice()
        {
            this.Fin_PaymentAdviceDetail = new HashSet<Fin_PaymentAdviceDetail>();
        }
    
        public decimal AdviceID { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<System.DateTime> PaymentEndDate { get; set; }
        public int PreparedBy { get; set; }
        public System.DateTime PreparationDate { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string PostStatus { get; set; }
        public Nullable<int> RevokedBy { get; set; }
        public Nullable<System.DateTime> RevokeDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public bool Locked4Validation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_PaymentAdviceDetail> Fin_PaymentAdviceDetail { get; set; }
    }
}
