//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_OpeningBalance
    {
        public int YrCode { get; set; }
        public string SubCode { get; set; }
        public int PCCode { get; set; }
        public decimal OpenBalDr { get; set; }
        public decimal OpenBalCr { get; set; }
        public long AccId { get; set; }
        public long SubId { get; set; }
        public Nullable<int> SubDivId { get; set; }
    }
}
