//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_SubsidaryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_SubsidaryType()
        {
            this.Fin_Subsidary = new HashSet<Fin_Subsidary>();
        }
    
        public int SubTypeId { get; set; }
        public string SubType { get; set; }
        public string AccCode { get; set; }
        public bool Status { get; set; }
        public string OldCode { get; set; }
        public int CatId { get; set; }
        public string Abbr { get; set; }
        public long AccId { get; set; }
    
        public virtual Fin_Accounts Fin_Accounts { get; set; }
        public virtual Fin_Category Fin_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Subsidary> Fin_Subsidary { get; set; }
    }
}
