//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_ProfitCenters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_ProfitCenters()
        {
            this.Fin_VoucherDetail = new HashSet<Fin_VoucherDetail>();
        }
    
        public int PCCode { get; set; }
        public string PCDesc { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public bool Status { get; set; }
        public string LocCode { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_VoucherDetail> Fin_VoucherDetail { get; set; }
    }
}
