//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BackendIncPolicyDtl
    {
        public long PolicyDtlId { get; set; }
        public int PolicyId { get; set; }
        public int TypeId { get; set; }
        public int ModelId { get; set; }
        public int SkuId { get; set; }
        public string SerialNo { get; set; }
        public decimal BasicTarget { get; set; }
        public decimal IncPercent { get; set; }
        public decimal SalesmanInc { get; set; }
        public decimal LowerPortion { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal SpecialInc { get; set; }
        public string PriceType { get; set; }
    
        public virtual Fin_BackendIncPolicy Fin_BackendIncPolicy { get; set; }
    }
}
