//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Year
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_Year()
        {
            this.Fin_Period = new HashSet<Fin_Period>();
            this.Fin_Voucher = new HashSet<Fin_Voucher>();
        }
    
        public int YrCode { get; set; }
        public string YrName { get; set; }
        public System.DateTime YrStart { get; set; }
        public System.DateTime YrEnd { get; set; }
        public string YrStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Period> Fin_Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Voucher> Fin_Voucher { get; set; }
    }
}
