//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_VoucherDetail
    {
        public long VrDtlId { get; set; }
        public long VrId { get; set; }
        public int PCCode { get; set; }
        public int CCCode { get; set; }
        public long AccId { get; set; }
        public Nullable<long> SubId { get; set; }
        public string Particulars { get; set; }
        public decimal Dr { get; set; }
        public decimal Cr { get; set; }
        public string ChequeNo { get; set; }
        public int TrxSeqId { get; set; }
        public Nullable<int> SubDivId { get; set; }
        public Nullable<long> RefId { get; set; }
        public string Instrument { get; set; }
        public string InstrumentNo { get; set; }
    
        public virtual Fin_Accounts Fin_Accounts { get; set; }
        public virtual Fin_Voucher Fin_Voucher { get; set; }
        public virtual Fin_ProfitCenters Fin_ProfitCenters { get; set; }
    }
}
