//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BackendIncDtl
    {
        public long TransDtlId { get; set; }
        public int TransId { get; set; }
        public int PolicyId { get; set; }
        public int TypeId { get; set; }
        public int ModelId { get; set; }
        public int SKUId { get; set; }
        public int ItemId { get; set; }
        public string SerialNo { get; set; }
        public int IncBaseId { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal IncPercent { get; set; }
        public decimal IncValue { get; set; }
        public decimal SalesmanInc { get; set; }
        public decimal LowerPortion { get; set; }
        public decimal SpecialInc { get; set; }
        public decimal CalculatedInc { get; set; }
        public decimal ApprovedInc { get; set; }
        public Nullable<int> LocId { get; set; }
        public string GRNNo { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string PriceType { get; set; }
    
        public virtual Fin_BackendInc Fin_BackendInc { get; set; }
    }
}
