//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_Period()
        {
            this.Fin_Voucher = new HashSet<Fin_Voucher>();
        }
    
        public int YrCode { get; set; }
        public int PrCode { get; set; }
        public string PrName { get; set; }
        public System.DateTime PrStart { get; set; }
        public System.DateTime PrEnd { get; set; }
        public string PrStatus { get; set; }
    
        public virtual Fin_Year Fin_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Voucher> Fin_Voucher { get; set; }
    }
}
