//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_VoucherCounter
    {
        public long CounterID { get; set; }
        public string VrTypeID { get; set; }
        public int YrCode { get; set; }
        public int PrCode { get; set; }
        public int Day { get; set; }
        public long YearCounter { get; set; }
        public long MonthCounter { get; set; }
        public long DayCounter { get; set; }
    
        public virtual Fin_VoucherTypes Fin_VoucherTypes { get; set; }
    }
}
