//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BankBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_BankBook()
        {
            this.Fin_BankBookCancelCheqs = new HashSet<Fin_BankBookCancelCheqs>();
        }
    
        public long TransID { get; set; }
        public long AccId { get; set; }
        public string StartChqNo { get; set; }
        public string EndChqNo { get; set; }
        public string CurrentChqNo { get; set; }
        public bool ActiveStatus { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public string AccountType { get; set; }
        public string BankName { get; set; }
        public string BankAccNo { get; set; }
    
        public virtual Fin_Accounts Fin_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BankBookCancelCheqs> Fin_BankBookCancelCheqs { get; set; }
    }
}
