//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Notes
    {
        public int RowId { get; set; }
        public long AccId { get; set; }
        public string Title { get; set; }
        public int SortOrder { get; set; }
        public int NoteId { get; set; }
        public int SubNoteId { get; set; }
        public int ReportTypeId { get; set; }
        public int Impact { get; set; }
        public Nullable<int> AccLevel { get; set; }
        public string Type { get; set; }
        public string Div { get; set; }
    }
}
