//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_Voucher()
        {
            this.Fin_BankBookTrans = new HashSet<Fin_BankBookTrans>();
            this.Fin_VoucherDetail = new HashSet<Fin_VoucherDetail>();
        }
    
        public long VrId { get; set; }
        public string VrTypeId { get; set; }
        public string VrNo { get; set; }
        public System.DateTime VrDate { get; set; }
        public string VrPaidTo { get; set; }
        public string VrStatus { get; set; }
        public int YrCode { get; set; }
        public int PrCode { get; set; }
        public string RefDocNo { get; set; }
        public Nullable<System.DateTime> RefDocDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RevokedBy { get; set; }
        public Nullable<System.DateTime> RevokedDate { get; set; }
        public string Remarks { get; set; }
        public int CompId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BankBookTrans> Fin_BankBookTrans { get; set; }
        public virtual Fin_Period Fin_Period { get; set; }
        public virtual Fin_VoucherTypes Fin_VoucherTypes { get; set; }
        public virtual Fin_Year Fin_Year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_VoucherDetail> Fin_VoucherDetail { get; set; }
    }
}
