//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_AcControls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_AcControls()
        {
            this.Fin_Accounts = new HashSet<Fin_Accounts>();
        }
    
        public string GrCode { get; set; }
        public string CnCode { get; set; }
        public string CnDesc { get; set; }
        public string BlCodeDr { get; set; }
        public string BlCodeCr { get; set; }
        public int CnId { get; set; }
        public int GrId { get; set; }
    
        public virtual Fin_AcGroups Fin_AcGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Accounts> Fin_Accounts { get; set; }
    }
}
