//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_CostType
    {
        public int CostTypeId { get; set; }
        public string CostType { get; set; }
        public Nullable<long> CapitalHOGL { get; set; }
        public Nullable<long> CapitalSHGL { get; set; }
        public Nullable<long> RevenueHOGL { get; set; }
        public Nullable<long> RevenueSHGL { get; set; }
        public bool Status { get; set; }
        public bool IsService { get; set; }
        public decimal DeprRate { get; set; }
        public Nullable<long> AccDeprHOGL { get; set; }
        public Nullable<long> DeprHOGL { get; set; }
        public Nullable<long> AccDeprSHGL { get; set; }
        public Nullable<long> DeprSHGL { get; set; }
    }
}
