//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_PaymentAdviceDetail
    {
        public decimal AdviceID { get; set; }
        public decimal AdviceDtlID { get; set; }
        public string SubCode { get; set; }
        public string ChequeName { get; set; }
        public string ChequeNo { get; set; }
        public decimal CheqValue { get; set; }
        public decimal LedgerClosingBal { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal TaxRate { get; set; }
        public decimal TaxAmount { get; set; }
        public bool isMerged { get; set; }
        public decimal MergeValue { get; set; }
    
        public virtual Fin_PaymentAdvice Fin_PaymentAdvice { get; set; }
    }
}
