//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Subsidary
    {
        public long SubId { get; set; }
        public string SubsidaryCode { get; set; }
        public string SubsidaryName { get; set; }
        public string SubCode { get; set; }
        public int SubTypeId { get; set; }
        public string OldCode { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> CityId { get; set; }
        public long AccId { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public bool Status { get; set; }
    
        public virtual Fin_SubsidaryType Fin_SubsidaryType { get; set; }
    }
}
