//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BRSDetail
    {
        public long DocDtlId { get; set; }
        public long DocId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Narration { get; set; }
        public string ChequeNo { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public decimal Balance { get; set; }
        public Nullable<long> VrDtlId { get; set; }
        public bool Status { get; set; }
    
        public virtual Fin_BRS Fin_BRS { get; set; }
    }
}
