//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_AcGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_AcGroups()
        {
            this.Fin_AcControls = new HashSet<Fin_AcControls>();
        }
    
        public string GrCode { get; set; }
        public string GrDesc { get; set; }
        public int ClsCode { get; set; }
        public int GrId { get; set; }
    
        public virtual Fin_AcClasses Fin_AcClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_AcControls> Fin_AcControls { get; set; }
    }
}
