//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_Accounts()
        {
            this.Fin_BankBook = new HashSet<Fin_BankBook>();
            this.Fin_SubsidaryType = new HashSet<Fin_SubsidaryType>();
            this.Fin_VoucherDetail = new HashSet<Fin_VoucherDetail>();
        }
    
        public string CnCode { get; set; }
        public string SubCode { get; set; }
        public string SubCodeDesc { get; set; }
        public bool IsLocked { get; set; }
        public string Remarks { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public long AccId { get; set; }
        public int CnId { get; set; }
        public int SubDivId { get; set; }
        public bool IsAGE { get; set; }
        public bool IsCarry { get; set; }
        public bool IsInvestment { get; set; }
        public bool Status { get; set; }
        public bool HasSub { get; set; }
        public bool IsHOGL { get; set; }
    
        public virtual Fin_AcControls Fin_AcControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BankBook> Fin_BankBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_SubsidaryType> Fin_SubsidaryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_VoucherDetail> Fin_VoucherDetail { get; set; }
    }
}
