//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_CostCenters
    {
        public long CCCode { get; set; }
        public string CCDesc { get; set; }
        public Nullable<int> LocId { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> PCCode { get; set; }
    }
}
