//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BRS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_BRS()
        {
            this.Fin_BRSDetail = new HashSet<Fin_BRSDetail>();
        }
    
        public long DocId { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public long AccId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BRSDetail> Fin_BRSDetail { get; set; }
    }
}
