//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BackendIncPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_BackendIncPolicy()
        {
            this.Fin_BackendIncPolicyDtl = new HashSet<Fin_BackendIncPolicyDtl>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int SupId { get; set; }
        public string IncTypeId { get; set; }
        public int IncBaseId { get; set; }
        public string Status { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BackendIncPolicyDtl> Fin_BackendIncPolicyDtl { get; set; }
    }
}
