//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_PeriodLog
    {
        public int TransId { get; set; }
        public int YrCode { get; set; }
        public int PrCode { get; set; }
        public string PrStatus { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    }
}
