//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_BankBookTrans
    {
        public long TransID { get; set; }
        public long VrId { get; set; }
        public int YrCode { get; set; }
        public int PrCode { get; set; }
        public long AccId { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeType { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentType { get; set; }
        public string Recipient { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string InstrumentNo { get; set; }
        public string InstrumentType { get; set; }
        public Nullable<long> BankBookId { get; set; }
    
        public virtual Fin_Voucher Fin_Voucher { get; set; }
    }
}
