//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_VoucherPostingLog
    {
        public long RowId { get; set; }
        public string VrTypeId { get; set; }
        public int TransTypeId { get; set; }
        public long TransId { get; set; }
        public long VrId { get; set; }
    }
}
