//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_VoucherTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fin_VoucherTypes()
        {
            this.Fin_Voucher = new HashSet<Fin_Voucher>();
            this.Fin_VoucherCounter = new HashSet<Fin_VoucherCounter>();
        }
    
        public string VrTypeId { get; set; }
        public string VrTypeDesc { get; set; }
        public string SubCode { get; set; }
        public string VtDbCr { get; set; }
        public string VtNumGeneration { get; set; }
        public string VtNumInitialization { get; set; }
        public string AllowBackDateEntry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_Voucher> Fin_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_VoucherCounter> Fin_VoucherCounter { get; set; }
    }
}
