//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockOpening
    {
        public int RowId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public string CompCode { get; set; }
        public string CompName { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> OpenYear { get; set; }
        public string SrNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> AgeDate { get; set; }
        public string TID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string City { get; set; }
        public string CityHint { get; set; }
        public string Install { get; set; }
        public string Zon { get; set; }
        public string Region { get; set; }
        public string Department { get; set; }
        public string Station { get; set; }
        public string EasyName { get; set; }
        public string ShortName { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
    }
}
