//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_POReturn()
        {
            this.Inv_POReturnDtl = new HashSet<Inv_POReturnDtl>();
        }
    
        public long PORId { get; set; }
        public string PORNo { get; set; }
        public System.DateTime PORDate { get; set; }
        public int SuppId { get; set; }
        public int LocId { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string ReturnType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POReturnDtl> Inv_POReturnDtl { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
    }
}
