//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PurchaseDetail
    {
        public long PInvDtl { get; set; }
        public long PInvId { get; set; }
        public int SKUId { get; set; }
        public int Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal Discount { get; set; }
        public decimal STax { get; set; }
        public decimal WHT { get; set; }
        public bool IsGiftItem { get; set; }
        public long PODtlId { get; set; }
        public decimal MRP { get; set; }
    
        public virtual Itm_Master Itm_Master { get; set; }
        public virtual Inv_Purchase Inv_Purchase { get; set; }
    }
}
