//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Suppliers()
        {
            this.Inv_PO = new HashSet<Inv_PO>();
            this.Inv_POReturn = new HashSet<Inv_POReturn>();
            this.Inv_Store = new HashSet<Inv_Store>();
            this.Inv_SuppliersCity = new HashSet<Inv_SuppliersCity>();
            this.Inv_SuppliersMapping = new HashSet<Inv_SuppliersMapping>();
            this.Itm_PPrice = new HashSet<Itm_PPrice>();
            this.Inv_Purchase = new HashSet<Inv_Purchase>();
            this.Fin_BackendIncPolicy = new HashSet<Fin_BackendIncPolicy>();
        }
    
        public int SuppId { get; set; }
        public string SuppName { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string PhoneOff { get; set; }
        public string PhoneRes { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> GST { get; set; }
        public int CategoryId { get; set; }
        public int PaymentTermId { get; set; }
        public string ChequeName { get; set; }
        public string GLCode { get; set; }
        public int UserID { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
        public long AccId { get; set; }
        public Nullable<int> OldSuppId { get; set; }
        public Nullable<long> SubId { get; set; }
        public string TaxAppliedOn { get; set; }
        public bool IsReg { get; set; }
        public string CompanyName { get; set; }
        public string RegisteredAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PO> Inv_PO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POReturn> Inv_POReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Store> Inv_Store { get; set; }
        public virtual Inv_SuppliersCat Inv_SuppliersCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SuppliersCity> Inv_SuppliersCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SuppliersMapping> Inv_SuppliersMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_PPrice> Itm_PPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Purchase> Inv_Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fin_BackendIncPolicy> Fin_BackendIncPolicy { get; set; }
    }
}
