//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_GRNDetail
    {
        public long GRNDtlId { get; set; }
        public long GRNId { get; set; }
        public long ItemId { get; set; }
        public int RcvdQty { get; set; }
        public int SKUStatus { get; set; }
        public decimal PP { get; set; }
        public long PODtlId { get; set; }
    
        public virtual Inv_GRN Inv_GRN { get; set; }
        public virtual Inv_Store Inv_Store { get; set; }
    }
}
