//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Store()
        {
            this.Inv_GRNDetail = new HashSet<Inv_GRNDetail>();
            this.Inv_IssueDetail = new HashSet<Inv_IssueDetail>();
        }
    
        public long ItemId { get; set; }
        public int SKUId { get; set; }
        public int LocId { get; set; }
        public int Qty { get; set; }
        public string SerialNo { get; set; }
        public decimal PPrice { get; set; }
        public decimal CPrice { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> SuppId { get; set; }
        public Nullable<int> FromLocId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public decimal MRP { get; set; }
        public string OldSerialNo { get; set; }
        public string CSerialNo { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<bool> Exempted { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<bool> IncExempt { get; set; }
        public Nullable<System.DateTime> IncExemptDate { get; set; }
        public string IncExemptBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_GRNDetail> Inv_GRNDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_IssueDetail> Inv_IssueDetail { get; set; }
        public virtual Inv_Status Inv_Status { get; set; }
        public virtual Itm_Master Itm_Master { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
        public virtual Comp_Locations Comp_Locations { get; set; }
    }
}
