//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BikeReg
    {
        public long RegId { get; set; }
        public long ItemId { get; set; }
        public string SaleType { get; set; }
        public long RefTransId { get; set; }
        public bool RegFeeStatus { get; set; }
        public decimal RegFeeCharges { get; set; }
        public string NumberPlate { get; set; }
        public bool NumberPlateStatus { get; set; }
        public bool RegDocStatus { get; set; }
        public bool TransferStatus { get; set; }
        public string TransferTo { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
    }
}
