//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_OpeningStockMobile
    {
        public long RowId { get; set; }
        public int SKUId { get; set; }
        public int LocId { get; set; }
        public string SerialNo { get; set; }
        public decimal PPrice { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> SuppId { get; set; }
        public decimal MRP { get; set; }
        public string CSerialNo { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool IsPosted { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<bool> Exempted { get; set; }
    }
}
