//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BikeReg_Old
    {
        public int RowId { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string AccNo { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string ItemName { get; set; }
        public string Model { get; set; }
        public string CompName { get; set; }
        public string SrNo { get; set; }
        public string Saletype { get; set; }
        public string RegFeesStatus { get; set; }
        public Nullable<decimal> RegFeesCharges { get; set; }
        public string NumberPlate { get; set; }
        public string NumberPlateStatus { get; set; }
        public string RegDocsStatus { get; set; }
        public string TransferStatus { get; set; }
        public string TransferTo { get; set; }
        public string MobileNo { get; set; }
        public string Address1 { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
