//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SuppCatGL
    {
        public int RowId { get; set; }
        public int CategoryId { get; set; }
        public long GLCode { get; set; }
        public int TypeId { get; set; }
    }
}
