//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POSchMaster
    {
        public long SchMasterId { get; set; }
        public System.DateTime SchDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public long POId { get; set; }
    }
}
