//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Customers()
        {
            this.Inv_SaleOrder = new HashSet<Inv_SaleOrder>();
        }
    
        public int CustId { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string CNIC { get; set; }
        public string NTN { get; set; }
        public string Email { get; set; }
        public string GLCode { get; set; }
        public int DaysLimit { get; set; }
        public string ChequeNo { get; set; }
        public string BankName { get; set; }
        public string AccountTitle { get; set; }
        public string BusinessRelation { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SaleOrder> Inv_SaleOrder { get; set; }
    }
}
