//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_OpeningStock
    {
        public long RowId { get; set; }
        public int LocId { get; set; }
        public long ItemId { get; set; }
        public System.DateTime TransDate { get; set; }
        public long UserId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> PPrice { get; set; }
    }
}
