//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POScheduleLog
    {
        public long RowId { get; set; }
        public long POSchId { get; set; }
        public long PODtlId { get; set; }
        public int LocId { get; set; }
        public int OrderQty { get; set; }
        public int OrderBy { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
