//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SuppliersMapping
    {
        public int RowId { get; set; }
        public int SupplierId { get; set; }
        public int ComId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    
        public virtual Itm_Company Itm_Company { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
    }
}
