//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POPayment
    {
        public long TransId { get; set; }
        public int LocId { get; set; }
        public long POInvId { get; set; }
        public decimal Amount { get; set; }
        public string PaidBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public Nullable<long> PaymentId { get; set; }
        public decimal Discount { get; set; }
    }
}
