//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_AdjOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_AdjOut()
        {
            this.Inv_AdjOutDetail = new HashSet<Inv_AdjOutDetail>();
        }
    
        public long TransId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public int LocId { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_AdjOutDetail> Inv_AdjOutDetail { get; set; }
    }
}
