//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Sale()
        {
            this.Inv_SaleDetail = new HashSet<Inv_SaleDetail>();
            this.Inv_SaleCreditReceive = new HashSet<Inv_SaleCreditReceive>();
        }
    
        public long TransId { get; set; }
        public int LocId { get; set; }
        public int TransactionTypeId { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public int CustId { get; set; }
        public string CustName { get; set; }
        public string CustCellNo { get; set; }
        public string CustCNIC { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Remarks { get; set; }
        public decimal ReceiveAmount { get; set; }
        public decimal Advance { get; set; }
        public int PaymentModeId { get; set; }
        public decimal Discount { get; set; }
        public Nullable<int> Salesman { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<long> RefSaleId { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<long> PaymentAccId { get; set; }
        public string FBRInvoiceNo { get; set; }
        public bool IsTaxable { get; set; }
        public string Response { get; set; }
        public string TInvoiceNo { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> OrderAdvance { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string CustNTN { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string CustAccountNo { get; set; }
        public string CustAccountHolder { get; set; }
        public string CustAccountTitle { get; set; }
        public string CustBankName { get; set; }
        public string BankTransId { get; set; }
        public string CustType { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SaleDetail> Inv_SaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SaleCreditReceive> Inv_SaleCreditReceive { get; set; }
    }
}
