//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SaleCreditReceive
    {
        public long TransId { get; set; }
        public int LocId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public int CustId { get; set; }
        public decimal ReceivedAmount { get; set; }
        public long SaleId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ReceivedFrom { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool IsPosted { get; set; }
    
        public virtual Inv_Sale Inv_Sale { get; set; }
        public virtual Comp_Locations Comp_Locations { get; set; }
    }
}
