//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SuppliersCity
    {
        public int RowId { get; set; }
        public int SuppId { get; set; }
        public int CityId { get; set; }
    
        public virtual Comp_City Comp_City { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
    }
}
