//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockAdj
    {
        public int RowId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public long ItemId { get; set; }
        public int FromSKUId { get; set; }
        public int LocId { get; set; }
        public int ToSKUId { get; set; }
        public decimal PPriceAdj { get; set; }
        public decimal MRPAdj { get; set; }
        public bool Status { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
    }
}
