//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_PO()
        {
            this.Inv_GRN = new HashSet<Inv_GRN>();
            this.Inv_PODetail = new HashSet<Inv_PODetail>();
            this.Inv_POMapping = new HashSet<Inv_POMapping>();
            this.Inv_Purchase = new HashSet<Inv_Purchase>();
        }
    
        public long POId { get; set; }
        public string PONo { get; set; }
        public int POTypeId { get; set; }
        public int SuppId { get; set; }
        public System.DateTime PODate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PaymentTerm { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
        public string MobileNo { get; set; }
        public string DeliveryAddress { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> PlanId { get; set; }
        public string PolicyType { get; set; }
        public decimal Discount { get; set; }
        public Nullable<int> RevokedBy { get; set; }
        public Nullable<System.DateTime> RevokedDate { get; set; }
        public bool POInvoiceStatus { get; set; }
        public string LCSuppName { get; set; }
        public string LCSuppMobile { get; set; }
        public string LCSuppAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_GRN> Inv_GRN { get; set; }
        public virtual Inv_POStatus Inv_POStatus { get; set; }
        public virtual Users_Login Users_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PODetail> Inv_PODetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POMapping> Inv_POMapping { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Purchase> Inv_Purchase { get; set; }
    }
}
