//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_SaleOrder()
        {
            this.Inv_SaleOrderDetail = new HashSet<Inv_SaleOrderDetail>();
        }
    
        public long TransId { get; set; }
        public int LocId { get; set; }
        public int TransactionTypeId { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public int CustId { get; set; }
        public string CustName { get; set; }
        public string CustCellNo { get; set; }
        public string CustCNIC { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Remarks { get; set; }
        public decimal Advance { get; set; }
        public int PaymentModeId { get; set; }
        public decimal Discount { get; set; }
        public Nullable<int> Salesman { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<long> RefSaleId { get; set; }
        public bool IsPosted { get; set; }
        public string Status { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<long> PaymentAccId { get; set; }
        public string OrderType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SaleOrderDetail> Inv_SaleOrderDetail { get; set; }
        public virtual Inv_Customers Inv_Customers { get; set; }
    }
}
