//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Issue()
        {
            this.Inv_IssueDetail = new HashSet<Inv_IssueDetail>();
        }
    
        public long TransId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int FromLocId { get; set; }
        public int ToLocId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_IssueDetail> Inv_IssueDetail { get; set; }
    }
}
