//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Purchase()
        {
            this.Inv_PurchaseDetail = new HashSet<Inv_PurchaseDetail>();
        }
    
        public long PInvId { get; set; }
        public string InvNo { get; set; }
        public System.DateTime InvDate { get; set; }
        public long RefInvNo { get; set; }
        public System.DateTime RefInvDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int SuppId { get; set; }
        public Nullable<long> POId { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Status { get; set; }
        public string VerifiedBy { get; set; }
        public string Purchaser { get; set; }
        public bool IsReturn { get; set; }
        public Nullable<int> OldTransId { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> RevokedBy { get; set; }
        public Nullable<System.DateTime> RevokedDate { get; set; }
        public string PaymentStatus { get; set; }
        public long GRNId { get; set; }
    
        public virtual Inv_PO Inv_PO { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
        public virtual Users_Login Users_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PurchaseDetail> Inv_PurchaseDetail { get; set; }
    }
}
