//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BikeLetter
    {
        public long TransId { get; set; }
        public long ItemId { get; set; }
        public string LetterNumber { get; set; }
        public bool LetterStatus { get; set; }
        public int EnvelopNo { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
    }
}
