//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SaleDiscount
    {
        public long RowId { get; set; }
        public long TransDtlId { get; set; }
        public decimal Disc { get; set; }
        public string Reason { get; set; }
        public string CareOf { get; set; }
    }
}
