//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StoreHistory
    {
        public long RowId { get; set; }
        public int LocId { get; set; }
        public int SKUId { get; set; }
        public long ItemId { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Type { get; set; }
        public int Qty { get; set; }
        public decimal PPrice { get; set; }
        public decimal SPrice { get; set; }
        public decimal MRP { get; set; }
        public decimal SMPrice { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public int MFact { get; set; }
        public Nullable<long> RefId { get; set; }
    }
}
