//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POReturnDtl
    {
        public long PORDtlId { get; set; }
        public long PORId { get; set; }
        public int SKUId { get; set; }
        public int Qty { get; set; }
        public string Remarks { get; set; }
        public decimal TP { get; set; }
        public long ItemId { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> STax { get; set; }
        public Nullable<decimal> MRP { get; set; }
    
        public virtual Inv_POReturn Inv_POReturn { get; set; }
        public virtual Itm_Master Itm_Master { get; set; }
    }
}
