//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_IssueDetail
    {
        public long TransDtlId { get; set; }
        public long TransId { get; set; }
        public long ItemId { get; set; }
        public int Qty { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PPrice { get; set; }
    
        public virtual Inv_Issue Inv_Issue { get; set; }
        public virtual Inv_Store Inv_Store { get; set; }
    }
}
