//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Complain
    {
        public long ComplainId { get; set; }
        public System.DateTime ComplainDate { get; set; }
        public long ItemId { get; set; }
        public long SKUId { get; set; }
        public string SrNo { get; set; }
        public string SaleType { get; set; }
        public long TransId { get; set; }
        public string Customer { get; set; }
        public string CustomerMobile { get; set; }
        public string Complain { get; set; }
        public string Communicator { get; set; }
        public string CommunicatorMobile { get; set; }
        public string CComplainNo { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public System.DateTime TransDate { get; set; }
        public long UserId { get; set; }
    }
}
