//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_POPlan()
        {
            this.Inv_POPlanMapping = new HashSet<Inv_POPlanMapping>();
            this.Inv_POPlanDetail = new HashSet<Inv_POPlanDetail>();
        }
    
        public long PlanId { get; set; }
        public int SuppId { get; set; }
        public int POTypeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
    
        public virtual Inv_POType Inv_POType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POPlanMapping> Inv_POPlanMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POPlanDetail> Inv_POPlanDetail { get; set; }
    }
}
