//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PODetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_PODetail()
        {
            this.Inv_POSchedule = new HashSet<Inv_POSchedule>();
        }
    
        public long PODtlId { get; set; }
        public long POId { get; set; }
        public int SKUId { get; set; }
        public int Qty { get; set; }
        public string Spec { get; set; }
        public Nullable<int> DiscPolicyId { get; set; }
        public Nullable<int> PairPolicyId { get; set; }
        public decimal PP { get; set; }
        public decimal TP { get; set; }
        public decimal MRP { get; set; }
        public decimal Discount { get; set; }
        public decimal GST { get; set; }
        public decimal WHT { get; set; }
        public bool IsGiftItem { get; set; }
        public decimal ExtraCharges { get; set; }
        public int CityId { get; set; }
        public decimal MonthlyIncentive { get; set; }
        public decimal QuarterlyIncentive { get; set; }
        public decimal BiannuallyIncentive { get; set; }
        public decimal AnnuallyIncentive { get; set; }
    
        public virtual Inv_PO Inv_PO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POSchedule> Inv_POSchedule { get; set; }
        public virtual Itm_Master Itm_Master { get; set; }
    }
}
