//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SaleDetail
    {
        public long TransDtlId { get; set; }
        public long TransId { get; set; }
        public long ItemId { get; set; }
        public int Qty { get; set; }
        public decimal SPrice { get; set; }
        public decimal PPrice { get; set; }
        public bool IsReturned { get; set; }
        public decimal Discount { get; set; }
        public decimal MRP { get; set; }
        public decimal SM { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> PrevStatus { get; set; }
        public Nullable<decimal> Gala { get; set; }
    
        public virtual Inv_Sale Inv_Sale { get; set; }
    }
}
