//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POPlanCityDetail
    {
        public long PlanDtlId { get; set; }
        public long PlanId { get; set; }
        public int SKUId { get; set; }
        public int Qty { get; set; }
        public int CityId { get; set; }
    
        public virtual Inv_POPlanCity Inv_POPlanCity { get; set; }
    }
}
