//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_SuppPayment
    {
        public long TransId { get; set; }
        public int SuppId { get; set; }
        public decimal ClosingBalance { get; set; }
        public decimal Payment { get; set; }
        public decimal Disc { get; set; }
        public decimal WHT { get; set; }
        public decimal BankAmount { get; set; }
        public Nullable<long> BankAccId { get; set; }
        public decimal CashAmount { get; set; }
        public bool IsWHTPaid { get; set; }
        public string InstrumentNo { get; set; }
        public string Instrument { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string PaidStatus { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public decimal Proposed { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool IsPosted { get; set; }
        public int LocId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Remarks { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<long> AccId { get; set; }
    }
}
