//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockVerificationDtl
    {
        public long DtlId { get; set; }
        public long DocId { get; set; }
        public long ItemId { get; set; }
        public string SerialNo { get; set; }
        public int SKUId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string InputType { get; set; }
        public string Remarks { get; set; }
    
        public virtual Inv_StockVerification Inv_StockVerification { get; set; }
    }
}
