//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_POPocket
    {
        public long TransId { get; set; }
        public long POId { get; set; }
        public int LocId { get; set; }
        public int SKUId { get; set; }
        public string SerialNo { get; set; }
        public bool Status { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    }
}
