//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_GRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_GRN()
        {
            this.Inv_GRNDetail = new HashSet<Inv_GRNDetail>();
        }
    
        public long GRNId { get; set; }
        public long POId { get; set; }
        public string GRNNo { get; set; }
        public System.DateTime GRNDate { get; set; }
        public string DONo { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public int LocId { get; set; }
        public int SuppId { get; set; }
        public int RcvdBy { get; set; }
        public System.DateTime RcvdDate { get; set; }
        public string Status { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    
        public virtual Inv_PO Inv_PO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_GRNDetail> Inv_GRNDetail { get; set; }
    }
}
