//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_BikeLetter_Old
    {
        public int RowId { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string DoNo { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public string SuppName { get; set; }
        public string ItemName { get; set; }
        public string Model { get; set; }
        public string CompName { get; set; }
        public string SrNo { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string LetterNumber { get; set; }
        public string LetterStatus { get; set; }
        public Nullable<decimal> EnvelopNo { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
