//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_PR()
        {
            this.Inv_PRDetail = new HashSet<Inv_PRDetail>();
        }
    
        public long PRId { get; set; }
        public string PRNo { get; set; }
        public int LocId { get; set; }
        public System.DateTime PRDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public long UserId { get; set; }
        public bool Status { get; set; }
        public string SuppId { get; set; }
        public string LCSuppName { get; set; }
        public string LCSuppMob { get; set; }
        public string LCSuppAddress { get; set; }
        public string PRStatus { get; set; }
        public Nullable<long> POId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PRDetail> Inv_PRDetail { get; set; }
    }
}
