//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PRDetail
    {
        public long PRDtlId { get; set; }
        public long PRId { get; set; }
        public Nullable<int> SKUId { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public string Remarks { get; set; }
    
        public virtual Inv_PR Inv_PR { get; set; }
    }
}
