//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_AdjOutDetail
    {
        public long TransDtlId { get; set; }
        public long TransId { get; set; }
        public long ItemId { get; set; }
        public int FromStatusId { get; set; }
        public int ToStatusId { get; set; }
        public decimal PPrice { get; set; }
        public int AdjTypeId { get; set; }
        public long AccId { get; set; }
    
        public virtual Inv_AdjOut Inv_AdjOut { get; set; }
        public virtual Inv_AdjType Inv_AdjType { get; set; }
    }
}
