//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ItemsDetail
    {
        public string ItemCode { get; set; }
        public string LocCode { get; set; }
        public string LocName { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public string Expire { get; set; }
        public string Status { get; set; }
        public string OldPcs { get; set; }
        public string Remarks { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public string City { get; set; }
        public string CityHint { get; set; }
        public string Install { get; set; }
        public string Zon { get; set; }
        public string Region { get; set; }
        public string Department { get; set; }
        public string Station { get; set; }
        public string EasyName { get; set; }
        public string ShortName { get; set; }
        public string FromLocation { get; set; }
        public Nullable<System.DateTime> AgeDate { get; set; }
        public string AssetType { get; set; }
        public string Fault { get; set; }
        public string Communicator { get; set; }
        public string ComplainNo { get; set; }
        public Nullable<System.DateTime> ComplainDate { get; set; }
        public string NewSrNo { get; set; }
    }
}
