//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_DiscountPolicySlab
    {
        public int RowId { get; set; }
        public int PolicyId { get; set; }
        public int MinSlabQty { get; set; }
        public int MaxSlabQty { get; set; }
        public decimal IncentiveAmt { get; set; }
        public decimal ExtraQtyRate { get; set; }
        public bool Status { get; set; }
        public string Tour { get; set; }
    
        public virtual Itm_DiscountPolicy Itm_DiscountPolicy { get; set; }
    }
}
