//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_PairPolicy
    {
        public int PolicyId { get; set; }
        public int ModelId { get; set; }
        public int RatioPurQty { get; set; }
        public int RatioGiftQty { get; set; }
        public int FOCModelId { get; set; }
        public decimal ExtraCharges { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    }
}
