//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_SerialPlan
    {
        public int RowId { get; set; }
        public long ItemId { get; set; }
        public System.DateTime EffectedDate { get; set; }
        public decimal BasePrice { get; set; }
        public decimal InstPrice { get; set; }
        public decimal Advance { get; set; }
        public decimal Inst { get; set; }
        public int Duration { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
