//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_PPrice
    {
        public long RowId { get; set; }
        public int SuppId { get; set; }
        public int SKUId { get; set; }
        public decimal TP { get; set; }
        public decimal MRP { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public decimal MonthlyIncentive { get; set; }
        public decimal QuarterlyIncentive { get; set; }
        public decimal BiannuallyIncentive { get; set; }
        public decimal AnnuallyIncentive { get; set; }
        public string Remarks { get; set; }
    
        public virtual Itm_Master Itm_Master { get; set; }
        public virtual Inv_Suppliers Inv_Suppliers { get; set; }
    }
}
