//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itm_Company()
        {
            this.Inv_SuppliersMapping = new HashSet<Inv_SuppliersMapping>();
            this.Itm_Type = new HashSet<Itm_Type>();
        }
    
        public int ComId { get; set; }
        public string ComName { get; set; }
        public string ComCode { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_SuppliersMapping> Inv_SuppliersMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_Type> Itm_Type { get; set; }
    }
}
