//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itm_Products()
        {
            this.Itm_Type = new HashSet<Itm_Type>();
            this.Itm_ProductClass = new HashSet<Itm_ProductClass>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
        public string ProductCode { get; set; }
        public string PCTCode { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_Type> Itm_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_ProductClass> Itm_ProductClass { get; set; }
    }
}
