//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_PDisc
    {
        public long RowId { get; set; }
        public int SuppId { get; set; }
        public int ProductId { get; set; }
        public int PDiscTypeId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    
        public virtual Itm_PDiscType Itm_PDiscType { get; set; }
    }
}
