//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_Barcode
    {
        public int RowId { get; set; }
        public int SKUId { get; set; }
        public string Barcode { get; set; }
    
        public virtual Itm_Master Itm_Master { get; set; }
    }
}
