//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_SPrice
    {
        public long RowId { get; set; }
        public int CityId { get; set; }
        public int LocId { get; set; }
        public int SKUId { get; set; }
        public decimal CashPrice { get; set; }
        public System.DateTime EffectedFrom { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
    
        public virtual Itm_Master Itm_Master { get; set; }
    }
}
