//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itm_Master()
        {
            this.Inv_PODetail = new HashSet<Inv_PODetail>();
            this.Inv_POReturnDtl = new HashSet<Inv_POReturnDtl>();
            this.Inv_Store = new HashSet<Inv_Store>();
            this.Itm_PPrice = new HashSet<Itm_PPrice>();
            this.Itm_SKUPlan = new HashSet<Itm_SKUPlan>();
            this.Itm_SPrice = new HashSet<Itm_SPrice>();
            this.Lse_Detail = new HashSet<Lse_Detail>();
            this.Itm_SKUPair = new HashSet<Itm_SKUPair>();
            this.Inv_PurchaseDetail = new HashSet<Inv_PurchaseDetail>();
            this.Itm_Barcode = new HashSet<Itm_Barcode>();
        }
    
        public int SKUId { get; set; }
        public string SKUCode { get; set; }
        public string SKUName { get; set; }
        public int ModelId { get; set; }
        public int WarrantyId { get; set; }
        public int ColorId { get; set; }
        public string OtherSpecs { get; set; }
        public string BarcodeValue { get; set; }
        public bool ActiveStatus { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> PairId { get; set; }
        public bool AvailableForSale { get; set; }
        public bool AvailableForPurchase { get; set; }
        public bool IsPair { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> UOMId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PODetail> Inv_PODetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_POReturnDtl> Inv_POReturnDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Store> Inv_Store { get; set; }
        public virtual Itm_Color Itm_Color { get; set; }
        public virtual Itm_Model Itm_Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_PPrice> Itm_PPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_SKUPlan> Itm_SKUPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_SPrice> Itm_SPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Detail> Lse_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_SKUPair> Itm_SKUPair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PurchaseDetail> Inv_PurchaseDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itm_Barcode> Itm_Barcode { get; set; }
    }
}
