//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_PlanPolicy
    {
        public int RowId { get; set; }
        public int LocId { get; set; }
        public int Duration { get; set; }
        public decimal MinAdvance { get; set; }
        public decimal MaxAdvance { get; set; }
        public decimal MarkUp { get; set; }
        public bool Status { get; set; }
    }
}
