//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_ProductClass
    {
        public int ProductClassId { get; set; }
        public string ProductClass { get; set; }
        public int ProductId { get; set; }
        public System.DateTime TransDate { get; set; }
        public long UserId { get; set; }
        public bool Status { get; set; }
    
        public virtual Itm_Products Itm_Products { get; set; }
    }
}
