//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itm_SaleRate
    {
        public long RowId { get; set; }
        public int SKUId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal SM { get; set; }
        public decimal SR { get; set; }
        public decimal SKT { get; set; }
        public decimal Gala { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Status { get; set; }
    }
}
