//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Cheque
    {
        public long ChequeId { get; set; }
        public long AccNo { get; set; }
        public string ChequeType { get; set; }
        public string ChequeNo { get; set; }
        public decimal ChequeAmount { get; set; }
        public bool IsChequeReturn { get; set; }
        public bool ChequeStatus { get; set; }
        public string BankName { get; set; }
        public string AccountTitle { get; set; }
        public string BranchName { get; set; }
        public string ChequeIssueTo { get; set; }
        public string ChequeReturnTo { get; set; }
        public string BankAccNo { get; set; }
        public string ChequeCNIC { get; set; }
        public string ChequeBy { get; set; }
    
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
