//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_ExpenseHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lse_ExpenseHead()
        {
            this.Lse_ExpenseTransaction = new HashSet<Lse_ExpenseTransaction>();
        }
    
        public int ExpHeadId { get; set; }
        public string ExpHead { get; set; }
        public string GLCode { get; set; }
        public decimal MaxLimit { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
        public int ExpTypeId { get; set; }
        public string ExpFor { get; set; }
        public Nullable<int> OldExpId { get; set; }
    
        public virtual Lse_ExpType Lse_ExpType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_ExpenseTransaction> Lse_ExpenseTransaction { get; set; }
    }
}
