//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_CashCollectionDetail
    {
        public long DocDtlId { get; set; }
        public long DocId { get; set; }
        public int CashHeadId { get; set; }
        public decimal CashAmount { get; set; }
        public string CashHead { get; set; }
    
        public virtual Lse_CashCollection Lse_CashCollection { get; set; }
    }
}
