//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Return
    {
        public long TransId { get; set; }
        public long AccNo { get; set; }
        public int LocId { get; set; }
        public int ReturnTypeId { get; set; }
        public string ItemType { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> NewAccNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public bool IsTaxable { get; set; }
        public string FBRInvoiceNo { get; set; }
        public string TInvoiceNo { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<bool> AICReturn { get; set; }
        public Nullable<bool> IncExempt { get; set; }
    
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
