//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_LatLng
    {
        public long RowId { get; set; }
        public long AccNo { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public string Type { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
    }
}
