//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lse_Master()
        {
            this.Lse_Cheque = new HashSet<Lse_Cheque>();
            this.Lse_Customer = new HashSet<Lse_Customer>();
            this.Lse_Detail = new HashSet<Lse_Detail>();
            this.Lse_Guarantor = new HashSet<Lse_Guarantor>();
            this.Lse_Installment = new HashSet<Lse_Installment>();
            this.Lse_Outstand = new HashSet<Lse_Outstand>();
            this.Lse_Return = new HashSet<Lse_Return>();
            this.Lse_CustomerTemplate = new HashSet<Lse_CustomerTemplate>();
            this.Lse_Audit = new HashSet<Lse_Audit>();
        }
    
        public long AccNo { get; set; }
        public int LocId { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public decimal ProcessFee { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CustName { get; set; }
        public string FName { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string NIC { get; set; }
        public decimal InstPrice { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> ActualAdvance { get; set; }
        public decimal Advance { get; set; }
        public decimal MonthlyInst { get; set; }
        public int Duration { get; set; }
        public string ProcessAt { get; set; }
        public int MktOfficerId { get; set; }
        public int InqOfficerId { get; set; }
        public int ManagerId { get; set; }
        public Nullable<int> SManagerId { get; set; }
        public Nullable<int> RMId { get; set; }
        public Nullable<int> CRCId { get; set; }
        public Nullable<int> SRMId { get; set; }
        public System.DateTime ProcessTransDate { get; set; }
        public Nullable<System.DateTime> DeliveryTransDate { get; set; }
        public Nullable<System.DateTime> CloseTransDate { get; set; }
        public int UserId { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OldAccNo { get; set; }
        public string MktOfficerCNIC { get; set; }
        public string InqOfficerCNIC { get; set; }
        public string ManagerCNIC { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Type { get; set; }
        public string FBRInvoiceNo { get; set; }
        public bool IsTaxable { get; set; }
        public string TInvoiceNo { get; set; }
        public bool IsLock { get; set; }
        public Nullable<int> AccSr { get; set; }
        public Nullable<int> BDMId { get; set; }
        public Nullable<decimal> OrderAdvance { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string AgingReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Cheque> Lse_Cheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Customer> Lse_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Detail> Lse_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Guarantor> Lse_Guarantor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Installment> Lse_Installment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Outstand> Lse_Outstand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Return> Lse_Return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_CustomerTemplate> Lse_CustomerTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Audit> Lse_Audit { get; set; }
        public virtual Comp_Locations Comp_Locations { get; set; }
    }
}
