//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Outstand
    {
        public long TransId { get; set; }
        public long AccNo { get; set; }
        public string Category { get; set; }
        public Nullable<int> RecoveryId { get; set; }
        public System.DateTime OutstandDate { get; set; }
        public decimal OutstandAmt { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
        public int LocId { get; set; }
        public Nullable<long> InstId { get; set; }
        public Nullable<System.DateTime> InstDate { get; set; }
        public Nullable<decimal> RecvAmt { get; set; }
        public bool IsAIC { get; set; }
        public string Remarks { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
