//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSE_CrcFinePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LSE_CrcFinePolicy()
        {
            this.LSE_CrcFinePolicyDtl = new HashSet<LSE_CrcFinePolicyDtl>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyCode { get; set; }
        public string PolicyDetail { get; set; }
        public string ShortDesc { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool Status { get; set; }
        public bool isCrcIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSE_CrcFinePolicyDtl> LSE_CrcFinePolicyDtl { get; set; }
    }
}
