//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_BlockCustomer
    {
        public long RowId { get; set; }
        public string CNIC { get; set; }
        public string CustomerName { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string CareOf { get; set; }
        public string Remarks { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
    }
}
