//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSE_CrcFinePolicyDtl
    {
        public int PolicyId { get; set; }
        public int PolicyDtlId { get; set; }
        public int DesgId { get; set; }
        public decimal FineAmt { get; set; }
    
        public virtual LSE_CrcFinePolicy LSE_CrcFinePolicy { get; set; }
    }
}
