//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_InstallmentLog
    {
        public long TransId { get; set; }
        public long InstId { get; set; }
        public System.DateTime InstDate { get; set; }
        public int LocId { get; set; }
        public long AccNo { get; set; }
        public decimal InstCharges { get; set; }
        public decimal Discount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PaidBy { get; set; }
    }
}
