//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_SMS
    {
        public long RowId { get; set; }
        public int LocId { get; set; }
        public string Category { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public long AccNo { get; set; }
        public string MobileNo { get; set; }
        public string SMS { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool IsUrdu { get; set; }
        public bool SendStatus { get; set; }
        public string Response { get; set; }
    }
}
