//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_CashPaymentHeads
    {
        public int RowId { get; set; }
        public string Head { get; set; }
        public long AccId { get; set; }
        public bool Status { get; set; }
        public bool HasSubsidary { get; set; }
    }
}
