//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_SearchCriteria
    {
        public int RowId { get; set; }
        public string Title { get; set; }
        public string Criteria { get; set; }
        public bool IsString { get; set; }
        public int SortOrder { get; set; }
        public bool Status { get; set; }
    }
}
