//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Audit
    {
        public long AuditId { get; set; }
        public long AccNo { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public bool Guarantor1 { get; set; }
        public bool Guarantor2 { get; set; }
        public bool Mobile { get; set; }
        public bool NIC { get; set; }
        public bool Cheque { get; set; }
        public bool Pic { get; set; }
        public bool Thumb { get; set; }
        public bool Affidavit { get; set; }
        public int Completion { get; set; }
        public bool BMSign { get; set; }
        public bool RMSign { get; set; }
        public bool VisitStatus { get; set; }
        public bool ObserveState { get; set; }
        public Nullable<System.DateTime> ObserveDate { get; set; }
        public bool VerifyStatus { get; set; }
        public string CRCRemarks { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<bool> WrongCase { get; set; }
        public Nullable<bool> WrongProduct { get; set; }
        public Nullable<bool> InvolvementCase { get; set; }
        public Nullable<bool> WrongPTO { get; set; }
        public Nullable<bool> PTOCase { get; set; }
        public Nullable<bool> HomeFake { get; set; }
        public Nullable<bool> OfficialFake { get; set; }
        public Nullable<bool> LoseGuarantee { get; set; }
        public Nullable<bool> FakeGuarantee { get; set; }
        public Nullable<bool> ManageGuarantee { get; set; }
        public Nullable<bool> WithoutVerification { get; set; }
        public Nullable<bool> HomeRental { get; set; }
        public Nullable<bool> PhotoCHQ { get; set; }
    
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
