//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_PendingRecovery
    {
        public long RowId { get; set; }
        public long InstId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Lse_Installment Lse_Installment { get; set; }
    }
}
