//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Detail
    {
        public long DtlId { get; set; }
        public long AccNo { get; set; }
        public Nullable<int> SKUId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public int Qty { get; set; }
        public decimal InstPrice { get; set; }
        public bool Status { get; set; }
        public decimal PPrice { get; set; }
        public bool IsReturned { get; set; }
        public decimal Discount { get; set; }
        public decimal MRP { get; set; }
        public decimal SM { get; set; }
        public string OldCompany { get; set; }
        public string OldProduct { get; set; }
        public string OldModel { get; set; }
        public string OldSerialNo { get; set; }
        public Nullable<long> InstPlanId { get; set; }
        public Nullable<decimal> dAdvance { get; set; }
        public Nullable<decimal> dInst { get; set; }
        public decimal Tax { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public string PlanType { get; set; }
        public Nullable<int> PrevStatus { get; set; }
    
        public virtual Itm_Master Itm_Master { get; set; }
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
