//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_SaleTarget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lse_SaleTarget()
        {
            this.Lse_SaleTargetLog = new HashSet<Lse_SaleTargetLog>();
        }
    
        public long TargetId { get; set; }
        public int TargetMonth { get; set; }
        public int TargetYear { get; set; }
        public int LocId { get; set; }
        public decimal Target { get; set; }
        public decimal TargetPDA { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TargetTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_SaleTargetLog> Lse_SaleTargetLog { get; set; }
        public virtual Lse_SaleTargetTypes Lse_SaleTargetTypes { get; set; }
        public virtual Comp_Locations Comp_Locations { get; set; }
    }
}
