//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_CrcFines
    {
        public long FineId { get; set; }
        public System.DateTime FineDate { get; set; }
        public Nullable<long> AccountNo { get; set; }
        public int FineToEmp { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public decimal FineAmt { get; set; }
        public string FineReason { get; set; }
        public int CRC { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> RMApproval { get; set; }
        public Nullable<System.DateTime> RMApprovalDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public bool IsLocked4Income { get; set; }
        public Nullable<int> LocId { get; set; }
    }
}
