//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Installment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lse_Installment()
        {
            this.Lse_PendingRecovery = new HashSet<Lse_PendingRecovery>();
        }
    
        public long InstId { get; set; }
        public System.DateTime InstDate { get; set; }
        public int LocId { get; set; }
        public long AccNo { get; set; }
        public decimal InstCharges { get; set; }
        public decimal Discount { get; set; }
        public decimal Fine { get; set; }
        public string FineType { get; set; }
        public Nullable<int> RecoveryId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string OldRecvCNIC { get; set; }
        public int PaidBy { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool IsLock { get; set; }
        public bool IsAIC { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_PendingRecovery> Lse_PendingRecovery { get; set; }
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
