//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_InstAdj
    {
        public long RowId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public long AccNo { get; set; }
        public int LocId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public int PaidBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public long OSId { get; set; }
    }
}
