//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_CashReceive
    {
        public long TransId { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public int LocId { get; set; }
        public Nullable<long> AccId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> CCCode { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<long> SubId { get; set; }
    }
}
