//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Guarantor
    {
        public long GuarantorId { get; set; }
        public long AccNo { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string NIC { get; set; }
        public string Occupation { get; set; }
        public string ResAddress { get; set; }
        public string OffAddress { get; set; }
        public string TelRes { get; set; }
        public string TelOff { get; set; }
        public string GRelation { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> GNo { get; set; }
    
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
