//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_CashCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lse_CashCollection()
        {
            this.Lse_CashCollectionDetail = new HashSet<Lse_CashCollectionDetail>();
        }
    
        public long DocId { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocType { get; set; }
        public int LocId { get; set; }
        public decimal CashPayable { get; set; }
        public decimal CashDeposit { get; set; }
        public decimal CashRcvdByCenter { get; set; }
        public long CashierId { get; set; }
        public Nullable<System.DateTime> CashierDate { get; set; }
        public string CashierRemarks { get; set; }
        public Nullable<int> CashCenterUserId { get; set; }
        public Nullable<System.DateTime> CashCenterRcvdDate { get; set; }
        public string CashCenterRemarks { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> AccId { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsVault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_CashCollectionDetail> Lse_CashCollectionDetail { get; set; }
        public virtual Comp_Locations Comp_Locations { get; set; }
    }
}
