//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_SMSSchedule
    {
        public int RowId { get; set; }
        public int LocId { get; set; }
        public string Category { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string SMS { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
    }
}
