//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_MOS
    {
        public long AccNo { get; set; }
        public System.DateTime Month { get; set; }
        public decimal TDue { get; set; }
        public decimal TPaid { get; set; }
        public decimal CMPaid { get; set; }
        public decimal ActDue { get; set; }
    }
}
