//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_Customer
    {
        public long CustId { get; set; }
        public long AccNo { get; set; }
        public System.DateTime CustomerDate { get; set; }
        public string Occupation { get; set; }
        public string ResAddress { get; set; }
        public string OffAddress { get; set; }
        public string Gender { get; set; }
        public string ResidentialStatus { get; set; }
        public decimal Salary { get; set; }
        public bool Affidavit { get; set; }
        public bool WrantyCard { get; set; }
        public bool Worth { get; set; }
        public bool Defaulter { get; set; }
        public bool AuditStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> PTO { get; set; }
        public Nullable<bool> SearchStatus { get; set; }
        public Nullable<bool> Pic { get; set; }
        public Nullable<bool> Thumb { get; set; }
    
        public virtual Lse_Master Lse_Master { get; set; }
    }
}
