//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lse_SaleTargetLog
    {
        public long LogId { get; set; }
        public long TargetId { get; set; }
        public int TargetMonth { get; set; }
        public int TargetYear { get; set; }
        public int LocId { get; set; }
        public decimal ActualTarget { get; set; }
        public decimal ModifiedTarget { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Lse_SaleTarget Lse_SaleTarget { get; set; }
    }
}
