//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpRole
    {
        public long RowId { get; set; }
        public int EmpId { get; set; }
        public int RoleId { get; set; }
        public bool Status { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
        public virtual Pay_Role Pay_Role { get; set; }
    }
}
