//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_AllowanceTrans
    {
        public long TransId { get; set; }
        public int EmpId { get; set; }
        public int AlwId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public string TransType { get; set; }
    }
}
