//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpPromotions
    {
        public long TransId { get; set; }
        public string TransType { get; set; }
        public int EmpId { get; set; }
        public int DeptId { get; set; }
        public int CurrentDesgId { get; set; }
        public int NewDesgId { get; set; }
        public decimal CurrentSalary { get; set; }
        public decimal NewSalary { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public string Reason { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> NewDeptId { get; set; }
        public Nullable<int> DesgId4Bank { get; set; }
        public Nullable<int> DesgId4Tax { get; set; }
    }
}
