//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalarySheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_SalarySheet()
        {
            this.Pay_SalarySheet_E = new HashSet<Pay_SalarySheet_E>();
        }
    
        public long SheetId { get; set; }
        public int HDeptId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int MonthDays { get; set; }
        public string ProcessType { get; set; }
        public int ProcessBy { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public bool IsPosted { get; set; }
        public bool IsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_SalarySheet_E> Pay_SalarySheet_E { get; set; }
    }
}
