//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpTransferLog
    {
        public long RowId { get; set; }
        public int EmpId { get; set; }
        public int FLocId { get; set; }
        public int TLocId { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string TrasferType { get; set; }
        public System.DateTime FDate { get; set; }
        public System.DateTime TDate { get; set; }
        public string TReason { get; set; }
        public bool Status { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
    }
}
