//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalaryDisbursement
    {
        public long TransId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int EmpId { get; set; }
        public long SheetDtlId { get; set; }
        public decimal SalaryRcvd { get; set; }
        public System.DateTime TransDate { get; set; }
        public int PaidBy { get; set; }
        public bool IsPosted { get; set; }
        public int LocId { get; set; }
        public int DisbursementTypeId { get; set; }
        public string DisbursementSource { get; set; }
    }
}
