//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_TargetIncentivePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_TargetIncentivePolicy()
        {
            this.Pay_TargetIncentivePolicyDetail = new HashSet<Pay_TargetIncentivePolicyDetail>();
            this.Pay_TargetIncentivePolicyLocations = new HashSet<Pay_TargetIncentivePolicyLocations>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public bool Status { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_TargetIncentivePolicyDetail> Pay_TargetIncentivePolicyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_TargetIncentivePolicyLocations> Pay_TargetIncentivePolicyLocations { get; set; }
    }
}
