//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpStatusLog
    {
        public int RowId { get; set; }
        public string StatusId { get; set; }
        public int EmpId { get; set; }
        public Nullable<int> LocId { get; set; }
        public Nullable<int> DesgId { get; set; }
        public Nullable<bool> FaceAllow { get; set; }
        public Nullable<bool> Finalized { get; set; }
        public Nullable<bool> BlockSalary { get; set; }
        public Nullable<bool> ManualSalary { get; set; }
        public Nullable<bool> AttendanceStatus { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
    }
}
