//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_CharityDonationTransDtl
    {
        public int CDId { get; set; }
        public long CDDtlId { get; set; }
        public int PersonId { get; set; }
        public decimal Amount { get; set; }
        public decimal Bank { get; set; }
        public decimal Tax { get; set; }
        public decimal Cash { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool isPosted { get; set; }
    
        public virtual Pay_CharityDonationTrans Pay_CharityDonationTrans { get; set; }
        public virtual Pay_CharityDonation Pay_CharityDonation { get; set; }
    }
}
