//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpReferences
    {
        public int TransId { get; set; }
        public int EmpId { get; set; }
        public string RefPerson { get; set; }
        public string RefContactNo { get; set; }
        public string RefCNIC { get; set; }
        public string RefAddress { get; set; }
        public byte[] RefProfession { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
    }
}
