//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpTaxSlabs
    {
        public int SlabId { get; set; }
        public decimal SlabStart { get; set; }
        public decimal SlabEnd { get; set; }
        public decimal TaxValue { get; set; }
        public decimal TaxRate { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinitionDate { get; set; }
    }
}
