//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalarySheet_VD
    {
        public long DSId { get; set; }
        public System.DateTime DSMonth { get; set; }
        public int LocId { get; set; }
        public int EmpId { get; set; }
        public int DesgId { get; set; }
        public decimal LedgerBal { get; set; }
        public decimal Salary { get; set; }
        public decimal Outstand { get; set; }
        public decimal ClosingAdv { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> ApprovedAdv { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
