//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalaryDisbursementControlPanel
    {
        public int PanelId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int HDeptId { get; set; }
        public int DeptId { get; set; }
        public Nullable<int> CityId { get; set; }
        public int DesignationId { get; set; }
        public int SectionId { get; set; }
        public bool AllowDisbursement { get; set; }
        public bool AllowFinalized { get; set; }
        public System.DateTime DisbursementStartDate { get; set; }
        public Nullable<System.DateTime> DisbursementEndDate { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int DisbursementTypeId { get; set; }
    }
}
