//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_IncentivePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_IncentivePolicy()
        {
            this.Pay_IncentivePolicyLocations = new HashSet<Pay_IncentivePolicyLocations>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public int DesgId { get; set; }
        public int AlwId { get; set; }
        public decimal IncVal { get; set; }
        public decimal IncPer { get; set; }
        public bool Status { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_IncentivePolicyLocations> Pay_IncentivePolicyLocations { get; set; }
    }
}
