//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpCheque
    {
        public long ChequeId { get; set; }
        public long EmpId { get; set; }
        public string ChequeType { get; set; }
        public string ChequeNo { get; set; }
        public string BankName { get; set; }
        public decimal ChequeAmount { get; set; }
        public bool IsChequeReturn { get; set; }
        public bool ChequeStatus { get; set; }
        public string ChequeLoc { get; set; }
    }
}
