//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_BasicSalaryPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_BasicSalaryPolicy()
        {
            this.Pay_BasicSalaryPolicyLocations = new HashSet<Pay_BasicSalaryPolicyLocations>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public int DesgId { get; set; }
        public int SlabId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public int PerformanceTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_BasicSalaryPolicyLocations> Pay_BasicSalaryPolicyLocations { get; set; }
    }
}
