//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_BankSalaryTransferDetail
    {
        public int BLId { get; set; }
        public long BLDtlId { get; set; }
        public int EmpId { get; set; }
        public decimal BankSalary { get; set; }
        public bool isPosted { get; set; }
        public long SheetDtlId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Pay_BankSalaryTransfer Pay_BankSalaryTransfer { get; set; }
    }
}
