//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpFineDetail
    {
        public long DocDtlId { get; set; }
        public int DocId { get; set; }
        public int EmpId { get; set; }
        public int FineTypeId { get; set; }
        public decimal FineActual { get; set; }
        public decimal FineApproved { get; set; }
        public string Remarks { get; set; }
    
        public virtual Pay_EmpFine Pay_EmpFine { get; set; }
        public virtual Pay_EmpFineType Pay_EmpFineType { get; set; }
    }
}
