//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpLoanTransaction
    {
        public int TransId { get; set; }
        public int LoanId { get; set; }
        public decimal DeductAmt { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool IsPosted { get; set; }
    
        public virtual Pay_EmpLoan Pay_EmpLoan { get; set; }
    }
}
