//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalaryDisbursementLog
    {
        public int TransId { get; set; }
        public Nullable<System.DateTime> SalaryMonth { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Exception { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DisbursementTypeId { get; set; }
        public string DisbursementSource { get; set; }
    }
}
