//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpBankSalary
    {
        public int RowId { get; set; }
        public int EmpId { get; set; }
        public decimal StartRange { get; set; }
        public decimal EndRange { get; set; }
        public bool IsFullBank { get; set; }
        public decimal BankSalary { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
    }
}
