//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_ProductIncCash
    {
        public int ProcessId { get; set; }
        public long RowId { get; set; }
        public int LocId { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public int Salesman { get; set; }
        public int TypeId { get; set; }
        public int ModelId { get; set; }
        public int SkuId { get; set; }
        public int ItemId { get; set; }
        public string SerialNo { get; set; }
        public decimal SPrice { get; set; }
        public int Qty { get; set; }
        public decimal Incentive { get; set; }
        public int PolicyId { get; set; }
        public long TransId { get; set; }
        public long TransDtlId { get; set; }
        public Nullable<decimal> SM { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string Remarks { get; set; }
    
        public virtual Pay_ProductInc Pay_ProductInc { get; set; }
    }
}
