//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalarySheet_E
    {
        public long SheetId { get; set; }
        public long SheetDtlId { get; set; }
        public int EmpId { get; set; }
        public int DesgId { get; set; }
        public int DeptId { get; set; }
        public string EmpStatus { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal BankSalary { get; set; }
        public int P { get; set; }
        public int L { get; set; }
        public int A { get; set; }
        public int T { get; set; }
        public bool isSalaryBlocked { get; set; }
        public string SalaryExp_AC { get; set; }
        public string Payable_AC { get; set; }
        public string Cash_AC { get; set; }
    
        public virtual Pay_SalarySheet Pay_SalarySheet { get; set; }
    }
}
