//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpPerformanceDetail
    {
        public long TransDtlId { get; set; }
        public int TransId { get; set; }
        public int LocId { get; set; }
        public int EmpId { get; set; }
        public decimal TargetQty { get; set; }
        public decimal TargetValue { get; set; }
        public decimal AchQty { get; set; }
        public decimal AchValue { get; set; }
        public decimal IncentivePercent { get; set; }
        public decimal IncentiveValue { get; set; }
        public decimal ApprovedValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DesgId { get; set; }
    
        public virtual Pay_EmpPerformance Pay_EmpPerformance { get; set; }
    }
}
