//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpBasicSalary
    {
        public int TransId { get; set; }
        public int LocId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int EmpId { get; set; }
        public int DesgId { get; set; }
        public decimal BasicSalary { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> BankSalary { get; set; }
    }
}
