//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_ProductIncPolicyDetail
    {
        public long PolicyDtlId { get; set; }
        public int PolicyId { get; set; }
        public int TypeId { get; set; }
        public int ModelId { get; set; }
        public int ProductClassId { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string SerialNo { get; set; }
        public string Condition { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public decimal IncAmount { get; set; }
        public int IncQty { get; set; }
    
        public virtual Pay_ProductIncPolicy Pay_ProductIncPolicy { get; set; }
    }
}
