//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_CharityDonationTrans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_CharityDonationTrans()
        {
            this.Pay_CharityDonationTransDtl = new HashSet<Pay_CharityDonationTransDtl>();
        }
    
        public int CDId { get; set; }
        public System.DateTime CDMonth { get; set; }
        public string ProcessType { get; set; }
        public int ProcessBy { get; set; }
        public System.DateTime ProcessDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CharityDonationTransDtl> Pay_CharityDonationTransDtl { get; set; }
    }
}
