//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_BranchStaffStrengthLog
    {
        public string LogId { get; set; }
        public int TransId { get; set; }
        public int DeptId { get; set; }
        public int DesgId { get; set; }
        public int ApprovedStrength { get; set; }
        public int UserId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
