//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpPerformance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_EmpPerformance()
        {
            this.Pay_EmpPerformanceDetail = new HashSet<Pay_EmpPerformanceDetail>();
        }
    
        public int TransId { get; set; }
        public System.DateTime PerformanceMonth { get; set; }
        public int PerformanceTypeId { get; set; }
        public int ProcessedBy { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual Pay_EmpPerformanceType Pay_EmpPerformanceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpPerformanceDetail> Pay_EmpPerformanceDetail { get; set; }
    }
}
