//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpSalary
    {
        public int TransId { get; set; }
        public int EmpId { get; set; }
        public string SalTypeId { get; set; }
        public decimal Salary { get; set; }
        public decimal BankSalary { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
        public virtual Pay_SalaryTypes Pay_SalaryTypes { get; set; }
    }
}
