//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Deduction
    {
        public int DedId { get; set; }
        public string DedName { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string GLCode { get; set; }
    }
}
