//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpHierarchy
    {
        public int LocId { get; set; }
        public Nullable<int> GMId { get; set; }
        public string GM { get; set; }
        public Nullable<int> SSRMId { get; set; }
        public string SSRM { get; set; }
        public Nullable<int> SRMId { get; set; }
        public string SRM { get; set; }
        public Nullable<int> BDMId { get; set; }
        public string BDM { get; set; }
        public Nullable<int> RMId { get; set; }
        public string RM { get; set; }
        public Nullable<int> CashHeadId { get; set; }
        public string CashHead { get; set; }
        public Nullable<int> RegionalCashHeadId { get; set; }
        public string RegionalCashHead { get; set; }
        public Nullable<int> CRCHeadId { get; set; }
        public string CRCHead { get; set; }
        public Nullable<int> RAuditorId { get; set; }
        public string RAuditor { get; set; }
        public Nullable<int> SAuditorId { get; set; }
        public string SAuditor { get; set; }
        public Nullable<int> AuditorId { get; set; }
        public string Auditor { get; set; }
        public Nullable<int> CashSaleCoordinatorId { get; set; }
        public string CashSaleCoordinator { get; set; }
        public Nullable<int> DGMId { get; set; }
        public string DGM { get; set; }
        public Nullable<int> SAssAuditorId { get; set; }
        public string SAssAuditor { get; set; }
    }
}
