//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_AICManager
    {
        public long TransId { get; set; }
        public int LocId { get; set; }
        public System.DateTime AicMonth { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public int DefinedBy { get; set; }
        public bool IsPosted { get; set; }
    }
}
