//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_CharityDonation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_CharityDonation()
        {
            this.Pay_CharityDonationTransDtl = new HashSet<Pay_CharityDonationTransDtl>();
        }
    
        public int PersonId { get; set; }
        public string PersonName { get; set; }
        public string CNIC { get; set; }
        public string ContactNo { get; set; }
        public string Reference { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> BankTransfer { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> CashierId { get; set; }
        public Nullable<int> CCC { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Remarks { get; set; }
        public string GLCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CharityDonationTransDtl> Pay_CharityDonationTransDtl { get; set; }
    }
}
