//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_AttendanceLog
    {
        public long LogId { get; set; }
        public long AttnId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime AttnDate { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
    
        public virtual Pay_Attendance Pay_Attendance { get; set; }
    }
}
