//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpTemplate
    {
        public int EmpId { get; set; }
        public string Template { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
    }
}
