//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Designation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_Designation()
        {
            this.Pay_DesignationLog = new HashSet<Pay_DesignationLog>();
            this.Pay_EmpMaster = new HashSet<Pay_EmpMaster>();
        }
    
        public int DesgId { get; set; }
        public string DesgName { get; set; }
        public bool Status { get; set; }
        public int ReportingTo { get; set; }
        public int SectionId { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_DesignationLog> Pay_DesignationLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpMaster> Pay_EmpMaster { get; set; }
    }
}
