//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_Department()
        {
            this.Pay_EmpMaster = new HashSet<Pay_EmpMaster>();
            this.Pay_DepartmentLog = new HashSet<Pay_DepartmentLog>();
        }
    
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public int LocId { get; set; }
        public int HDeptId { get; set; }
        public bool Status { get; set; }
        public int CCCode { get; set; }
    
        public virtual Pay_HDepartment Pay_HDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpMaster> Pay_EmpMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_DepartmentLog> Pay_DepartmentLog { get; set; }
    }
}
