//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpLeave
    {
        public long LeaveId { get; set; }
        public int EmpId { get; set; }
        public string LeaveTypeId { get; set; }
        public string LeaveCatId { get; set; }
        public System.DateTime LeaveFromDate { get; set; }
        public System.DateTime LeaveToDate { get; set; }
        public string LeaveReason { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedByHR { get; set; }
        public Nullable<System.DateTime> ApprovedDateHR { get; set; }
        public string RemarksByHR { get; set; }
        public string LeaveStatus { get; set; }
    
        public virtual Pay_LeaveCategory Pay_LeaveCategory { get; set; }
        public virtual Pay_LeaveTypes Pay_LeaveTypes { get; set; }
    }
}
