//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpTemplateFace
    {
        public int EmpId { get; set; }
        public int FacePositionXc { get; set; }
        public int FacePositionYc { get; set; }
        public int FacePositionW { get; set; }
        public float FacePositionAngle { get; set; }
        public int Eye1X { get; set; }
        public int Eye1Y { get; set; }
        public int Eye2X { get; set; }
        public int Eye2Y { get; set; }
        public byte[] Template { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    }
}
