//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalaryDisbursementTypes
    {
        public int DisbursementTypeId { get; set; }
        public string DisbursementType { get; set; }
        public bool IsActive { get; set; }
    }
}
