//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_SalarySheet_TI
    {
        public long TIId { get; set; }
        public System.DateTime TIMonth { get; set; }
        public string TIType { get; set; }
        public int LocId { get; set; }
        public int EmpId { get; set; }
        public int DesgId { get; set; }
        public decimal IncAmount { get; set; }
        public decimal UsedInClosing { get; set; }
        public decimal IncPayable { get; set; }
        public decimal ApprovedIncPayable { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool isPaid { get; set; }
        public Nullable<int> DisbursementTypeId { get; set; }
        public bool isPosted { get; set; }
        public Nullable<bool> AllowDisbursement { get; set; }
        public Nullable<decimal> OtherInc { get; set; }
        public string Remarks { get; set; }
    }
}
