//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_ProductInc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_ProductInc()
        {
            this.Pay_ProductIncCash = new HashSet<Pay_ProductIncCash>();
            this.Pay_ProductIncInst = new HashSet<Pay_ProductIncInst>();
        }
    
        public int ProcessId { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int CityId { get; set; }
        public int ProcessBy { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_ProductIncCash> Pay_ProductIncCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_ProductIncInst> Pay_ProductIncInst { get; set; }
    }
}
