//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_Attendance()
        {
            this.Pay_AttendanceLog = new HashSet<Pay_AttendanceLog>();
        }
    
        public long AttnId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime AttnDate { get; set; }
        public int LocId { get; set; }
        public System.DateTime InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<int> OutLocId { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string IPAddress { get; set; }
        public string AttnType { get; set; }
        public bool IsVerified { get; set; }
        public string AttnTypeOut { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<decimal> LatOut { get; set; }
        public Nullable<decimal> LngOut { get; set; }
    
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_AttendanceLog> Pay_AttendanceLog { get; set; }
    }
}
