//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpBank
    {
        public int TransId { get; set; }
        public int EmpId { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNumber { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public string AccountStatus { get; set; }
    }
}
