//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_EmpMaster()
        {
            this.Lse_Installment = new HashSet<Lse_Installment>();
            this.Lse_Outstand = new HashSet<Lse_Outstand>();
            this.Pay_Attendance = new HashSet<Pay_Attendance>();
            this.Pay_AttendanceFinal = new HashSet<Pay_AttendanceFinal>();
            this.Pay_DepartmentLog = new HashSet<Pay_DepartmentLog>();
            this.Pay_DesignationLog = new HashSet<Pay_DesignationLog>();
            this.Pay_Education = new HashSet<Pay_Education>();
            this.Pay_EmpLocationMapping = new HashSet<Pay_EmpLocationMapping>();
            this.Pay_EmpSalary = new HashSet<Pay_EmpSalary>();
            this.Pay_EmpRole = new HashSet<Pay_EmpRole>();
            this.Pay_Experience = new HashSet<Pay_Experience>();
            this.Pay_EmpReferences = new HashSet<Pay_EmpReferences>();
            this.Pay_EmpTransferLog = new HashSet<Pay_EmpTransferLog>();
        }
    
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string FName { get; set; }
        public string StatusId { get; set; }
        public int DesgId { get; set; }
        public int DeptId { get; set; }
        public int ShiftId { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public string Remarks { get; set; }
        public string RefPerson { get; set; }
        public string RefContactNo { get; set; }
        public string RefCNIC { get; set; }
        public string RefAddress { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PayScaleId { get; set; }
        public Nullable<int> Weekend { get; set; }
        public Nullable<int> WeeklyHoliday { get; set; }
        public string JobType { get; set; }
        public Nullable<int> EmpId_Old { get; set; }
        public string FNIC { get; set; }
        public bool RejoinBanned { get; set; }
        public string RejoinBannedReason { get; set; }
        public Nullable<int> AppointmentTypeId { get; set; }
        public Nullable<int> LocId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> AttendanceStatus { get; set; }
        public Nullable<bool> BlockSalary { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public Nullable<bool> IsFaceAllow { get; set; }
        public Nullable<bool> MSalary { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CNICExpireDate { get; set; }
        public Nullable<bool> IsZakat { get; set; }
        public Nullable<bool> SalaryException { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Installment> Lse_Installment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lse_Outstand> Lse_Outstand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Attendance> Pay_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_AttendanceFinal> Pay_AttendanceFinal { get; set; }
        public virtual Pay_Department Pay_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_DepartmentLog> Pay_DepartmentLog { get; set; }
        public virtual Pay_Designation Pay_Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_DesignationLog> Pay_DesignationLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Education> Pay_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpLocationMapping> Pay_EmpLocationMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpSalary> Pay_EmpSalary { get; set; }
        public virtual Pay_EmpTemplate Pay_EmpTemplate { get; set; }
        public virtual Pay_EmpStatus Pay_EmpStatus { get; set; }
        public virtual Pay_Shift Pay_Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpRole> Pay_EmpRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Experience> Pay_Experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpReferences> Pay_EmpReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpTransferLog> Pay_EmpTransferLog { get; set; }
    }
}
