//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_ProductIncPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_ProductIncPolicy()
        {
            this.Pay_ProductIncPolicyLocations = new HashSet<Pay_ProductIncPolicyLocations>();
            this.Pay_ProductIncPolicyDetail = new HashSet<Pay_ProductIncPolicyDetail>();
        }
    
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public System.DateTime PolicyStartDate { get; set; }
        public System.DateTime PolicyExpiryDate { get; set; }
        public bool PolicyStatus { get; set; }
        public string SaleType { get; set; }
        public string Remarks { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_ProductIncPolicyLocations> Pay_ProductIncPolicyLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_ProductIncPolicyDetail> Pay_ProductIncPolicyDetail { get; set; }
    }
}
