//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_BasicSalarySlab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_BasicSalarySlab()
        {
            this.Pay_BasicSalarySlabDtl = new HashSet<Pay_BasicSalarySlabDtl>();
        }
    
        public int SlabId { get; set; }
        public string SlabTitle { get; set; }
        public bool Status { get; set; }
        public int DefinedBy { get; set; }
        public System.DateTime DefinedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_BasicSalarySlabDtl> Pay_BasicSalarySlabDtl { get; set; }
    }
}
