//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpTax
    {
        public long TransId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public int EmpId { get; set; }
        public decimal MonthSalary { get; set; }
        public decimal AnnualSalary { get; set; }
        public decimal MedicalALW { get; set; }
        public decimal ConveyanceALW { get; set; }
        public decimal AnnualSalaryTaxable { get; set; }
        public decimal MonthSalaryTaxable { get; set; }
        public decimal AnnualTax { get; set; }
        public decimal MonthlyTax { get; set; }
        public decimal MonthSalaryPayable { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
    }
}
