//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_AttendanceFinalData
    {
        public long RowId { get; set; }
        public int EmpId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string StatusId { get; set; }
        public int UserId { get; set; }
        public string AttnType { get; set; }
        public string Reason { get; set; }
        public System.DateTime TransDate { get; set; }
        public int WorkingHours { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> MinutesLate { get; set; }
    
        public virtual Pay_AttendanceStatus Pay_AttendanceStatus { get; set; }
        public virtual Pay_EmpMaster Pay_EmpMaster { get; set; }
    }
}
