//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_EmpLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_EmpLoan()
        {
            this.Pay_EmpLoanTransaction = new HashSet<Pay_EmpLoanTransaction>();
        }
    
        public int LoanId { get; set; }
        public int LoanTypeID { get; set; }
        public int EmpId { get; set; }
        public decimal LoanAmt { get; set; }
        public decimal Inst { get; set; }
        public decimal LoanBal { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DedStartDate { get; set; }
        public bool AutoDeduct { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> AdvTypeID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PaidLocation { get; set; }
        public string PaymentMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_EmpLoanTransaction> Pay_EmpLoanTransaction { get; set; }
    }
}
