//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_PayScales
    {
        public int BPS { get; set; }
        public int MinSalary { get; set; }
        public int Increment { get; set; }
        public int MaxSalary { get; set; }
        public int Stages { get; set; }
        public string BPSTitle { get; set; }
    }
}
