//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_SINDetail
    {
        public long SINDtlId { get; set; }
        public long SINId { get; set; }
        public int ItemId { get; set; }
        public decimal Qty { get; set; }
        public decimal CPrice { get; set; }
        public string ItemType { get; set; }
        public Nullable<long> StoreId { get; set; }
        public string SerialNo { get; set; }
        public int CostTypeId { get; set; }
        public decimal RtnQty { get; set; }
    
        public virtual Pro_SIN Pro_SIN { get; set; }
    }
}
