//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_SIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_SIN()
        {
            this.Pro_SINDetail = new HashSet<Pro_SINDetail>();
        }
    
        public long SINId { get; set; }
        public string SINNo { get; set; }
        public System.DateTime SINDate { get; set; }
        public string Type { get; set; }
        public long MTRId { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public int CCCode { get; set; }
        public int FromLocId { get; set; }
        public int ToLocId { get; set; }
        public Nullable<long> ReturnId { get; set; }
        public string TransType { get; set; }
    
        public virtual Pro_MTR Pro_MTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_SINDetail> Pro_SINDetail { get; set; }
    }
}
