//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_PO()
        {
            this.Pro_PODetail = new HashSet<Pro_PODetail>();
        }
    
        public long POId { get; set; }
        public string PONo { get; set; }
        public long MTRId { get; set; }
        public int SuppId { get; set; }
        public System.DateTime PODate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public int PaymentTerm { get; set; }
        public string Status { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public string Remarks { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int NatureId { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<int> RevokedBy { get; set; }
        public Nullable<System.DateTime> RevokedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_PODetail> Pro_PODetail { get; set; }
    }
}
