//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_PODetail
    {
        public long PODtlId { get; set; }
        public long POId { get; set; }
        public int ItemId { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal Tax { get; set; }
        public decimal Disc { get; set; }
        public int LocId { get; set; }
        public decimal RecvQty { get; set; }
        public Nullable<int> CostTypeId { get; set; }
    
        public virtual Pro_Item Pro_Item { get; set; }
        public virtual Pro_PO Pro_PO { get; set; }
    }
}
