//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_ItemProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_ItemProduct()
        {
            this.Pro_Item = new HashSet<Pro_Item>();
        }
    
        public int ItemProductId { get; set; }
        public int ItemCategoryId { get; set; }
        public string ItemProduct { get; set; }
        public bool Status { get; set; }
        public string ItemProductCode { get; set; }
        public Nullable<int> CostTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_Item> Pro_Item { get; set; }
        public virtual Pro_ItemCategory Pro_ItemCategory { get; set; }
    }
}
