//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_GRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_GRN()
        {
            this.Pro_GRNDetail = new HashSet<Pro_GRNDetail>();
        }
    
        public long GRNId { get; set; }
        public string GRNNo { get; set; }
        public long POId { get; set; }
        public System.DateTime GRNDate { get; set; }
        public int LocId { get; set; }
        public string RecvBy { get; set; }
        public string RefInvNo { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public int SuppId { get; set; }
        public string Type { get; set; }
        public Nullable<long> ReturnId { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_GRNDetail> Pro_GRNDetail { get; set; }
    }
}
