//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_Stock
    {
        public long RowId { get; set; }
        public string DocType { get; set; }
        public int ItemId { get; set; }
        public int MFact { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public long RefDocId { get; set; }
        public int LocId { get; set; }
        public Nullable<int> CCode { get; set; }
        public decimal Qty { get; set; }
        public decimal PPrice { get; set; }
        public string DocNo { get; set; }
        public decimal OutQty { get; set; }
        public int SuppId { get; set; }
    
        public virtual Pro_Item Pro_Item { get; set; }
    }
}
