//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_MTRDetail
    {
        public long MTRDtlId { get; set; }
        public long MTRId { get; set; }
        public int ItemId { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> EstPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> RecvQty { get; set; }
        public string ItemType { get; set; }
    
        public virtual Pro_MTR Pro_MTR { get; set; }
    }
}
