//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_Item()
        {
            this.Pro_GRNDetail = new HashSet<Pro_GRNDetail>();
            this.Pro_PODetail = new HashSet<Pro_PODetail>();
            this.Pro_Stock = new HashSet<Pro_Stock>();
        }
    
        public int ItemId { get; set; }
        public string ItemCode { get; set; }
        public string Item { get; set; }
        public int ItemBrandId { get; set; }
        public int ItemProductId { get; set; }
        public int UOMId { get; set; }
        public string Spec { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_GRNDetail> Pro_GRNDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_PODetail> Pro_PODetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_Stock> Pro_Stock { get; set; }
        public virtual Pro_ItemBrand Pro_ItemBrand { get; set; }
        public virtual Pro_ItemProduct Pro_ItemProduct { get; set; }
        public virtual Itm_UOM Itm_UOM { get; set; }
    }
}
