//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_ItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pro_ItemCategory()
        {
            this.Pro_ItemProduct = new HashSet<Pro_ItemProduct>();
        }
    
        public int ItemCategoryId { get; set; }
        public string ItemCategory { get; set; }
        public bool Status { get; set; }
        public int ItemNatureId { get; set; }
        public string ItemCategoryCode { get; set; }
    
        public virtual Pro_ItemNature Pro_ItemNature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pro_ItemProduct> Pro_ItemProduct { get; set; }
    }
}
