//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tax_Invoice()
        {
            this.Tax_InvoiceItems = new HashSet<Tax_InvoiceItems>();
        }
    
        public long TransId { get; set; }
        public string InvoiceNumber { get; set; }
        public long POSID { get; set; }
        public string USIN { get; set; }
        public string RefUSIN { get; set; }
        public System.DateTime DateTime { get; set; }
        public string BuyerName { get; set; }
        public string BuyerNTN { get; set; }
        public string BuyerCNIC { get; set; }
        public string BuyerPhoneNumber { get; set; }
        public decimal TotalSaleValue { get; set; }
        public decimal TotalTaxCharged { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> FurtherTax { get; set; }
        public decimal TotalBillAmount { get; set; }
        public int PaymentMode { get; set; }
        public int InvoiceType { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<int> Code { get; set; }
        public string Response { get; set; }
        public bool SyncStatus { get; set; }
        public int TotalQuantity { get; set; }
        public long RefTransId { get; set; }
        public string Type { get; set; }
        public int LocId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_InvoiceItems> Tax_InvoiceItems { get; set; }
    }
}
