//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_InvoiceItems
    {
        public long TransDtlId { get; set; }
        public long TransId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PCTCode { get; set; }
        public int Quantity { get; set; }
        public double TaxRate { get; set; }
        public decimal SaleValue { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> FurtherTax { get; set; }
        public decimal TaxCharged { get; set; }
        public decimal TotalAmount { get; set; }
        public int InvoiceType { get; set; }
        public string RefUSIN { get; set; }
        public long RefTransDtlId { get; set; }
    
        public virtual Tax_Invoice Tax_Invoice { get; set; }
    }
}
