//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_MobileMenuObject
    {
        public int ObjectId { get; set; }
        public int ActivityId { get; set; }
        public string ObjectName { get; set; }
        public string ObjectAction { get; set; }
    }
}
