//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Feedback
    {
        public int RowId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime TransDate { get; set; }
        public int UserId { get; set; }
    }
}
