//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_Login()
        {
            this.Inv_PO = new HashSet<Inv_PO>();
            this.Users_Notifications = new HashSet<Users_Notifications>();
            this.Inv_Purchase = new HashSet<Inv_Purchase>();
            this.Crm_Response = new HashSet<Crm_Response>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public int GroupId { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool Status { get; set; }
        public string SessionId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsFirstLogin { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ThemeName { get; set; }
        public string DeviceId { get; set; }
        public string ConnectionId { get; set; }
        public Nullable<bool> AllowExternalAccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_PO> Inv_PO { get; set; }
        public virtual Users_Group Users_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Notifications> Users_Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Purchase> Inv_Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crm_Response> Crm_Response { get; set; }
    }
}
