//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_UserMenuObjectAccess
    {
        public int RowId { get; set; }
        public int ObjectId { get; set; }
        public int MenuId { get; set; }
        public int UserId { get; set; }
    
        public virtual Users_MenuObject Users_MenuObject { get; set; }
    }
}
