//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_NotificationMapping
    {
        public int RowId { get; set; }
        public int NotiTypeId { get; set; }
        public int GroupId { get; set; }
        public string NotiType { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
