//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Notifications
    {
        public long Id { get; set; }
        public string Notification { get; set; }
        public int UserId { get; set; }
        public bool IsSeen { get; set; }
        public Nullable<long> RefId { get; set; }
        public string RefLink { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public int SentBy { get; set; }
    
        public virtual Users_Login Users_Login { get; set; }
    }
}
