//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Chat
    {
        public long RowId { get; set; }
        public int FromId { get; set; }
        public int ToId { get; set; }
        public string Message { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool IsSeen { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
        public bool IsFile { get; set; }
    }
}
