//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_MenuObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_MenuObject()
        {
            this.Users_GroupMenuObjectAccess = new HashSet<Users_GroupMenuObjectAccess>();
            this.Users_UserMenuObjectAccess = new HashSet<Users_UserMenuObjectAccess>();
        }
    
        public int ObjectId { get; set; }
        public int MenuId { get; set; }
        public string ObjectName { get; set; }
        public string ObjectAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_GroupMenuObjectAccess> Users_GroupMenuObjectAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_UserMenuObjectAccess> Users_UserMenuObjectAccess { get; set; }
        public virtual Users_Menu Users_Menu { get; set; }
    }
}
