//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_LoginLog
    {
        public long RowId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string IP { get; set; }
        public string Session { get; set; }
        public string ComputerName { get; set; }
    }
}
