//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGEERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHierarchy
    {
        public int LocId { get; set; }
        public string GMId { get; set; }
        public string GM { get; set; }
        public string SSRMId { get; set; }
        public string SSRM { get; set; }
        public string SRMId { get; set; }
        public string SRM { get; set; }
        public string BDMId { get; set; }
        public string BDM { get; set; }
        public string RMId { get; set; }
        public string RM { get; set; }
    }
}
